name: xepa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  formz: ^0.4.1
  shared_preferences: ^2.0.11
  http: ^0.13.4
  intl: ^0.17.0
  device_preview: ^1.0.0

  auto_size_text: ^3.0.0

  flutter_svg: 1.0.0
  shimmer: ^2.0.0

  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.2 # https://pub.dev/packages/flutter_launcher_icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
